version: '3.4'

services:
  app:
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - gem_cache:/usr/local/bundle/gems
    env_file: ./backend/.env
    environment:
      RAILS_ENV: development
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - redis
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: newpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  web:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "81:81"
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:5.2
  #   environment:
  #     PMA_HOST: db
  #     MYSQL_ROOT_PASSWORD: newpassword
  #     PMA_PORT: 3306
  #   ports:
  #     - "8090:80"
  #   depends_on:
  #     - db
  # Redis
  redis:
    image: redis:4.0-alpine
  mailcatcher:
    image: dockage/mailcatcher:0.6.5
    ports:
      - 1025:1025
      - 1080:1080

  # nginx:
  #   image: nginx:alpine
  #   links:
  #     - web:web
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - web
  #   volumes:
  #     - backend/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #     - backend/docker/nginx/logs:/var/log/nginx
  #     - backend/docker/nginx/html:/etc/nginx/html
volumes:
  mysql-data:
  gem_cache:
